
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Mar 16 02:20:21 CST 2017
//----------------------------------------------------

package Graphik.AnalizadorG1;

/** CUP generated class containing symbol constants. */
public class sGF1 {
  /* terminals */
  public static final int vacioL = 8;
  public static final int boolL = 7;
  public static final int parC = 43;
  public static final int menor = 61;
  public static final int mod = 67;
  public static final int parA = 42;
  public static final int privadoL = 11;
  public static final int yLogico = 53;
  public static final int heredaL = 17;
  public static final int printL = 37;
  public static final int comparacion = 56;
  public static final int alsL = 13;
  public static final int archivoGK = 72;
  public static final int punto = 41;
  public static final int imports = 12;
  public static final int suma = 62;
  public static final int varL = 2;
  public static final int llamarL = 14;
  public static final int decimalL = 4;
  public static final int aumento = 69;
  public static final int div = 65;
  public static final int resta = 63;
  public static final int dosPuntos = 49;
  public static final int cadena = 77;
  public static final int corC = 47;
  public static final int corA = 46;
  public static final int menorIgual = 59;
  public static final int protegidoL = 10;
  public static final int forL = 26;
  public static final int decimal = 74;
  public static final int mentira = 39;
  public static final int dolar = 71;
  public static final int continueL = 29;
  public static final int notLogico = 52;
  public static final int indice = 70;
  public static final int llamarhkL = 16;
  public static final int xorLogico = 55;
  public static final int extencion2 = 40;
  public static final int elseL = 22;
  public static final int caracter = 76;
  public static final int asignacion = 50;
  public static final int delimitador = 51;
  public static final int id = 75;
  public static final int doL = 28;
  public static final int mainL = 19;
  public static final int mayorIgual = 58;
  public static final int columnaL = 33;
  public static final int caseL = 24;
  public static final int whileL = 27;
  public static final int publicoL = 9;
  public static final int llaveC = 45;
  public static final int mayor = 60;
  public static final int llaveA = 44;
  public static final int dondeL = 34;
  public static final int breakL = 30;
  public static final int retornarL = 18;
  public static final int cadenaL = 6;
  public static final int EOF = 0;
  public static final int dondeTodoL = 36;
  public static final int defaultL = 25;
  public static final int voidL = 32;
  public static final int incluirHK = 20;
  public static final int ifL = 21;
  public static final int error = 1;
  public static final int dondeCadaL = 35;
  public static final int caracterL = 5;
  public static final int disminucion = 68;
  public static final int distinto = 57;
  public static final int switchL = 23;
  public static final int pot = 66;
  public static final int por = 64;
  public static final int graficar = 31;
  public static final int enteroL = 3;
  public static final int coma = 48;
  public static final int oLogico = 54;
  public static final int verdad = 38;
  public static final int num = 73;
  public static final int newL = 15;
}

