/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DibujarFigura;


import Logica.*;
import arbol.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Point;
import java.awt.ScrollPane;
import java.io.*;
import java.util.*;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;


/**
 *
 * @author Alberth
 */
public class pruebasLienzo extends javax.swing.JFrame {

    //inicia tabla de simbolos
    public static String tablaErrores="";//<html><head><title>ERRORES</title></head><body><h1>"+diaL+"</h1><h1>"+horaL+"</h1><center><h1>ERRORES</h1><table border=1><tr><th>Linea</th><th>Columna</th><th>Tipo Error</th><th>Descripcion</th></tr>";
    public static String tablaSimbolosM="";
    static int cantErrores=0;
    static int cantSimbolos=0;
    //finaliza tabla de simbolos
    
    int contLineas=1;
    int fila=0;
    int col=0;
    int posAbs=0;
                        
    //JPanel panelito;
    public JTextArea edicion;
    public JScrollPane scrollPane;
    LineNr nr;
    int valorTiempo=100;
    int indiceDePestanha=0;
    
    //todo para el editor en su funcionamiento
    JFileChooser Ventana =  new JFileChooser(System.getProperty("user.dir")); //buscador de archivos
    String contenidoArchivo="";
    String path = ""; //Path
    HashMap<Integer,String> listaDeArchivosAbiertos = new HashMap<Integer,String>();
    int indexPT=0;
    //fin de todo lo usado
    
    //variables usadas para que funcione el guardar
        String texto="";
    //termina seccion guardar
    
        //para compilar
            static Analizador1.proyecto  calc=null;
            ArrayList<Nodo_variable> tablaSimbolos;

    public ArrayList<Nodo_variable> getTablaSimbolos() {
        return tablaSimbolos;
    }

    public void setTablaSimbolos(ArrayList<Nodo_variable> tablaSimbolo) {
        for(int cont=0;cont<tablaSimbolo.size();cont++){
             tablaSimbolos.add(new Nodo_variable(tablaSimbolo.get(cont).nombre ,tablaSimbolo.get(cont).valor,tablaSimbolo.get(cont).ambito,
                     tablaSimbolo.get(cont).acceso,tablaSimbolo.get(cont).posicion,tablaSimbolo.get(cont).tipo,tablaSimbolo.get(cont).tDato,
                     tablaSimbolo.get(cont).parametros,tablaSimbolo.get(cont).tamanho,tablaSimbolo.get(cont).heredado,
                    tablaSimbolo.get(cont).prioridad,tablaSimbolo.get(cont).nodoParametro,tablaSimbolo.get(cont).ubicacion));
             cantSimbolos++;
        }
    }
        //termina compilar
    public static Calendar calendario = new GregorianCalendar();
    public static int hora, minutos, segundos,dia,mes,anho;
    public static String diaL="";
    public static String horaL="";
    
    /**
     * Creates new form pruebasLienzo
     */
    public pruebasLienzo() {
        initComponents();
        crearNuevaPestanha();
        valorTiempo=100;
        indexPT=0;
        texto="";
        hora();
        tablaSimbolos=new ArrayList<>();
        tablaSimbolosM="";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JSeparator();
        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        jFrame4 = new javax.swing.JFrame();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        lblLiniaColumna = new javax.swing.JLabel();
        btnEjecutar = new javax.swing.JButton();
        btnDebuggear = new javax.swing.JButton();
        sliderTiempo = new javax.swing.JSlider();
        btnMostrarErrores = new javax.swing.JButton();
        jSeparator9 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuCrear = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        menuAbrir = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        menuGuardar = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        menuGuardarComo = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        menuSalir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuEjecutar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuDebuggear = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        menuVelocidad = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuError = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        menuTablaSimbolo = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        menuManualUsuario = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        menuManualTecnico = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame4Layout = new javax.swing.GroupLayout(jFrame4.getContentPane());
        jFrame4.getContentPane().setLayout(jFrame4Layout);
        jFrame4Layout.setHorizontalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame4Layout.setVerticalGroup(
            jFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        lblLiniaColumna.setText("-- | --");

        btnEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DibujarFigura/ejecutar.png"))); // NOI18N
        btnEjecutar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnEjecutarMouseMoved(evt);
            }
        });
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        btnDebuggear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DibujarFigura/debug2.png"))); // NOI18N
        btnDebuggear.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDebuggearMouseMoved(evt);
            }
        });

        sliderTiempo.setMaximum(10000);
        sliderTiempo.setMinimum(10);
        sliderTiempo.setPaintLabels(true);
        sliderTiempo.setPaintTicks(true);
        sliderTiempo.setSnapToTicks(true);
        sliderTiempo.setValue(100);
        sliderTiempo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderTiempoStateChanged(evt);
            }
        });
        sliderTiempo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sliderTiempoMouseMoved(evt);
            }
        });

        btnMostrarErrores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DibujarFigura/reporte.png"))); // NOI18N
        btnMostrarErrores.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnMostrarErroresMouseMoved(evt);
            }
        });
        btnMostrarErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarErroresActionPerformed(evt);
            }
        });

        jMenu3.setText("Archivo");

        menuCrear.setText("Crear");
        menuCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearActionPerformed(evt);
            }
        });
        jMenu3.add(menuCrear);
        jMenu3.add(jSeparator2);

        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirActionPerformed(evt);
            }
        });
        jMenu3.add(menuAbrir);
        jMenu3.add(jSeparator3);

        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarActionPerformed(evt);
            }
        });
        jMenu3.add(menuGuardar);
        jMenu3.add(jSeparator4);

        menuGuardarComo.setText("Guardar Como");
        menuGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGuardarComoActionPerformed(evt);
            }
        });
        jMenu3.add(menuGuardarComo);
        jMenu3.add(jSeparator5);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        jMenu3.add(menuSalir);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Herramientas");

        menuEjecutar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DibujarFigura/ejecutar.png"))); // NOI18N
        menuEjecutar.setText("Ejecutar");
        menuEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEjecutarActionPerformed(evt);
            }
        });
        jMenu4.add(menuEjecutar);
        jMenu4.add(jSeparator1);

        menuDebuggear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DibujarFigura/debug2.png"))); // NOI18N
        menuDebuggear.setText("Debuggear");
        jMenu4.add(menuDebuggear);
        jMenu4.add(jSeparator6);

        menuVelocidad.setText("Velocidad");
        jMenu4.add(menuVelocidad);

        jMenuBar1.add(jMenu4);

        jMenu1.setText("Mostrar");

        menuError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/DibujarFigura/reporte.png"))); // NOI18N
        menuError.setText("Errores");
        menuError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuErrorActionPerformed(evt);
            }
        });
        jMenu1.add(menuError);
        jMenu1.add(jSeparator8);

        menuTablaSimbolo.setText("Tabla Simbolos");
        menuTablaSimbolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablaSimboloActionPerformed(evt);
            }
        });
        jMenu1.add(menuTablaSimbolo);
        jMenu1.add(jSeparator11);

        menuManualUsuario.setText("Manual Usuario");
        menuManualUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManualUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(menuManualUsuario);
        jMenu1.add(jSeparator10);

        menuManualTecnico.setText("Manual Tecnico");
        menuManualTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuManualTecnicoActionPerformed(evt);
            }
        });
        jMenu1.add(menuManualTecnico);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator9)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDebuggear, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sliderTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarErrores, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLiniaColumna)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEjecutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDebuggear, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnMostrarErrores)
                            .addComponent(sliderTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLiniaColumna)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
               // indiceDePestanha=jTabbedPane1.getSelectedIndex();
               // JTextArea encontro=ObtenerAreaTexto();
       // fiCol(encontro);
    }//GEN-LAST:event_formWindowActivated

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        
        guardarArchivo();
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void btnEjecutarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEjecutarMouseMoved
                this.btnEjecutar.setToolTipText("Ejecutar");
    }//GEN-LAST:event_btnEjecutarMouseMoved

    private void btnDebuggearMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDebuggearMouseMoved
       this.btnDebuggear.setToolTipText("Debuggear");
    }//GEN-LAST:event_btnDebuggearMouseMoved

    private void btnMostrarErroresMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMostrarErroresMouseMoved
        this.btnMostrarErrores.setToolTipText("Mostrar Errores");
    }//GEN-LAST:event_btnMostrarErroresMouseMoved

    private void sliderTiempoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sliderTiempoMouseMoved
        this.sliderTiempo.setToolTipText("Estoy en: "+valorTiempo+" ms");
    }//GEN-LAST:event_sliderTiempoMouseMoved

    private void sliderTiempoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderTiempoStateChanged
        valorTiempo=sliderTiempo.getValue();
    }//GEN-LAST:event_sliderTiempoStateChanged

    private void menuCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearActionPerformed
        crearNuevaPestanha();
    }//GEN-LAST:event_menuCrearActionPerformed

    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        indexPT=jTabbedPane1.getSelectedIndex();
        abrirArchivo();
         
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarComoActionPerformed
       guardarArchivoComo();
    }//GEN-LAST:event_menuGuardarComoActionPerformed

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
       this.dispose();
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuErrorActionPerformed
         LienzoDibujo ld = new LienzoDibujo(this, true, "C:\\Users\\Alberth\\Pictures");
        
        ld.dibujarOvalo(100, 100,50,100,"BA3519", 1);
        ld.dibujarRectangulo(200, 200,50,100,"BA3519", 1);
        ld.dibujarTexto("holita",100, 100,"BA3519");
        ld.dibujarPunto(300, 300,"BA3519",50, 1);
        ld.setVisible(true);
       
        mostrarErrores();
        
        
    }//GEN-LAST:event_menuErrorActionPerformed

    private void menuEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEjecutarActionPerformed
        try {
            compilar();
        } catch (Exception ex) {
            Logger.getLogger(pruebasLienzo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuEjecutarActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        try {
            compilar();
        } catch (Exception ex) {
            Logger.getLogger(pruebasLienzo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        indiceDePestanha=jTabbedPane1.getSelectedIndex();
        JTextArea encontro=ObtenerAreaTexto();
        fiCol(encontro);
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnMostrarErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarErroresActionPerformed
        mostrarErrores();
    }//GEN-LAST:event_btnMostrarErroresActionPerformed

    private void menuTablaSimboloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablaSimboloActionPerformed
        mostrarTablaSimbolos();
    }//GEN-LAST:event_menuTablaSimboloActionPerformed

    private void menuManualUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManualUsuarioActionPerformed
        abrir("manualUsuario");
    }//GEN-LAST:event_menuManualUsuarioActionPerformed

    private void menuManualTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuManualTecnicoActionPerformed
        abrir("manualTecnico");
    }//GEN-LAST:event_menuManualTecnicoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(pruebasLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(pruebasLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(pruebasLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(pruebasLienzo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new pruebasLienzo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDebuggear;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnMostrarErrores;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JFrame jFrame4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblLiniaColumna;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuCrear;
    private javax.swing.JMenuItem menuDebuggear;
    private javax.swing.JMenuItem menuEjecutar;
    private javax.swing.JMenuItem menuError;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuGuardarComo;
    private javax.swing.JMenuItem menuManualTecnico;
    private javax.swing.JMenuItem menuManualUsuario;
    private javax.swing.JMenuItem menuSalir;
    private javax.swing.JMenuItem menuTablaSimbolo;
    private javax.swing.JMenuItem menuVelocidad;
    private javax.swing.JSlider sliderTiempo;
    // End of variables declaration//GEN-END:variables

  private void crearNuevaPestanha(){
        JPanel frame=new JPanel();
        frame.setLayout(new BorderLayout());
        final LineNr nr = new LineNr ();
        frame.add (nr, BorderLayout.WEST);
        frame.add (nr.scrollPan, BorderLayout.CENTER);
        jTabbedPane1.addTab("nuevo", frame);
  }          
    
void fiCol(final JTextArea re) {
    //jTextArea2.addCaretListener(new CaretListener(){
    re.addCaretListener(new CaretListener(){
        @Override
    public void caretUpdate(CaretEvent ching){
            try {
                //int posAbs=jTextArea2.getCaretPosition();//toma la posicion absoluta de la letra encontrada
                     posAbs=re.getCaretPosition();//.getCaretPosition();//toma la posicion absoluta de la letra encontrada
                        //int fila=jTextArea2.getLineOfOffset(posAbs);//encuentra la fila donde se encuentra
                         fila=re.getLineOfOffset(posAbs);//encuentra la fila donde se encuentra
                       // int col=posAbs-jTextArea2.getLineStartOffset(fila);//muestra en pantalla columna y fila de ubicacion de la letra
                          col=posAbs-re.getLineStartOffset(fila);//muestra en pantalla columna y fila de ubicacion de la letra
                        lblLiniaColumna.setText("Col: " +col+"|"+"Fil "+fila);//muestra en pantalla columna y fila de ubicacion de la letra
            } catch (BadLocationException ex) {
                Logger.getLogger(pruebasLienzo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
});
}
 
 public JTextArea ObtenerAreaTexto(){
    JPanel ma=(JPanel) jTabbedPane1.getComponent(indiceDePestanha);
    JScrollPane jsp = (JScrollPane) ma.getComponent(1);
    JTextArea jta=(JTextArea)jsp.getViewport().getComponent(0);
    return jta;
}   

 public void abrirArchivo(){
         abrirArFil(".lz","Lz","LZ"); 
            edicion=new JTextArea();
    
        String nombre=retornoNombreArchivo(path);
        
        Boolean comprovarSiGuardo=guardarProducto(indexPT+1,path,listaDeArchivosAbiertos);
        
        if(comprovarSiGuardo){
//            edicion.getDocument().insertString(0, "", null);
//            jTabbedPane1.addTab(nombre,new JScrollPane(edicion));
              JPanel frame=new JPanel();

  frame.setLayout(new BorderLayout());
     nr = new LineNr ();
    frame.add (nr, BorderLayout.WEST);
    frame.add (nr.scrollPan, BorderLayout.CENTER);
    
    jTabbedPane1.addTab(nombre, frame);
            filtro(path);
        }else{
            JOptionPane.showMessageDialog( rootPane, "No se puede introducir el archivo. El nombre esta repetido.", "Error archivo repetido.", JOptionPane.WARNING_MESSAGE); //Mensaje por si se prduce un error
        }
            
   

 }
         
 void abrirArFil(String forma1,String forma2,String forma3){
     Ventana.setAcceptAllFileFilterUsed(false); //elimino la opción "todos los archivos
     FileNameExtensionFilter ext = new FileNameExtensionFilter(forma1,forma2,forma3); //Le indico que busque solamente archivos con extensión .LFO
    // System.out.println("Entro en abrir");
     Ventana.setFileFilter(ext);
     filtro(forma1,forma2,forma3);
} 
 
       
void filtro (String forma1,String forma2, String forma3){
    Ventana.setAcceptAllFileFilterUsed(false); //elimino la opción "todos los archivos
FileNameExtensionFilter beirut = new FileNameExtensionFilter(forma1, forma2, forma3); //Le indico que busque solamente archivos con extensión .practlfp
Ventana.setFileFilter(beirut); //le agrego el componente.
int kaiserChiefs = Ventana.showOpenDialog(this); //reconocerá la opción escogida por el usuario.

if(kaiserChiefs == JFileChooser.APPROVE_OPTION) //validación "OK".
{ //INICIO IF
try { //INICIO TRY
path = Ventana.getSelectedFile().getAbsolutePath(); //Obtengo path.
}catch (Exception e){   
}
}
}

   public void filtro(String patito){
contenidoArchivo="";
FileReader arcticMonkeys = null; //Lector.
BufferedReader coldplay = null; //Buffer.
String arcadeFire = ""; //Texto leído.
String brightEyes = ""; //Path
//System.out.println("path de patito--> "+patito);
nr.agregarTexto("");
 //limpio la caja de texto.
//edicion.setEditable(true); //permito que el usuario la pueda editar.

try { //INICIO TRY
brightEyes = patito;//franzFerdinand.getSelectedFile().getAbsolutePath(); //Obtengo path.

if(new File(brightEyes).exists()) { //Verifico si el fichero existe.


arcticMonkeys = new FileReader(brightEyes/*animalCollective*/); //Leera el fichero.
coldplay = new BufferedReader(arcticMonkeys); //Almacenara contenido de fichero.

try { //INICIO TRY

while((arcadeFire = coldplay.readLine())!=null) //Leo linea por linea.
{ //INICIO WHILE
contenidoArchivo+=arcadeFire+"\n";
} //FIN WHILE
nr.agregarTexto(contenidoArchivo);//.setText(contenidoArchivo);
} //FIN TRY

catch (IOException ex)
{ //INICIO CATCH
//Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex); //Manejo de excepciones.
} // FIN CATCH
} //FIN IF

else
{ //INICIO ELSE
JOptionPane.showMessageDialog(rootPane, "El archivo seleccionado puede estar dañado", "Error en lectura", JOptionPane.ERROR_MESSAGE); //Mensaje por si se prduce un error
} // FIN ELSE

} //FIN TRY

catch (FileNotFoundException ex)
{ //INICIO CATCH
//Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex); //Manejo de excepciones.
} //FIN CATCH

finally { //INICIO FINALLY

try { //INICIO TRY
if (null != coldplay) //Validación archivo.
coldplay.close(); //Cerrar archivo.
} //FIN TRY

catch (IOException ex)
{ //INICIO CATCH
//Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex); //Manejo de excepciones.
} //FIN CATCH

} //FIN FINALLY
}

    
    public String retornoNombreArchivo(String path){
         File pr=new File(path);
    return pr.getName();
    }
            
    public Boolean guardarProducto(int pos, String path, HashMap <Integer,String> listaArchivosAbiertos){
//    if (listaArchivosAbiertos.containsKey(pos)){
//        System.out.println("No se puede introducir el producto. El nombre esta repetido.");
//        return false;
//    }
//    else{
        listaArchivosAbiertos.put(pos, path);               
        return true;
//    }
}
    
    public  void mostrarArchivosAbiertos(HashMap<Integer, String> listaProductos){
    int clave;
    Iterator<Integer> productos = listaProductos.keySet().iterator();
    System.out.println("Hay los siguientes productos:");
    String s="";
    while(productos.hasNext()){
        clave = productos.next();
        System.out.println(clave + " - " + listaProductos.get(clave));
    }        
}
    
    public String devolverPathArchivoAbierto(int index,HashMap<Integer, String> listaProductos){
         int clave;
        Iterator<Integer> productos = listaProductos.keySet().iterator();
    System.out.println("Hay los siguientes productos:");
    String s="No_existe-1";
    while(productos.hasNext()){
        clave = productos.next();
        if(index==clave){
            s=listaProductos.get(index);
            System.out.println("Archivo encontrado --> "+clave + " - " + listaProductos.get(clave));
        }
    }   
    return s;
    }
    
    
    public void guardarArchivo(){
         indiceDePestanha=jTabbedPane1.getSelectedIndex();    
        String path=jTabbedPane1.getTitleAt(indiceDePestanha);

        if(path.equalsIgnoreCase("nuevo")){
            guardarArchivoComo();
        }else{
            
            JTextArea encontro=ObtenerAreaTexto();
            String pathTemporal=devolverPathArchivoAbierto(indiceDePestanha,listaDeArchivosAbiertos);
            if(pathTemporal.equalsIgnoreCase("no_existe-1")){
                
            }else{
                System.out.println("clave temporal --> "+pathTemporal);
                Guardar(pathTemporal,encontro);
            }
            
        }
            
        
        
    }
    
     void Guardar (String path,JTextArea roma) //Guardar el TextArea
{       texto=roma.getText();
        try{
            PrintWriter ouPt=new PrintWriter(new FileWriter(path));
            ouPt.println(texto);
            ouPt.close();
        }catch(IOException e){
            System.out.println(e);
        }
}
     
     public void guardarArchivoComo(){
          try {
              indexPT=jTabbedPane1.getSelectedIndex();
              indiceDePestanha=jTabbedPane1.getSelectedIndex();
         guardarComo();
         Boolean comprovarSiGuardo=guardarProducto(indexPT+1,path,listaDeArchivosAbiertos);
         if(comprovarSiGuardo){
             JOptionPane.showMessageDialog( rootPane, "Archivo Almacenado exitosamente.", "Guardar Como.", JOptionPane.WARNING_MESSAGE); //Mensaje por si se prduce un error
         }else{
             JOptionPane.showMessageDialog( rootPane, "No se puede introducir el archivo. El nombre esta repetido.", "Error archivo repetido.", JOptionPane.WARNING_MESSAGE); //Mensaje por si se prduce un error
         }
         jTabbedPane1.setTitleAt(indexPT,retornoNombreArchivo(path)+".lz" );
             
     } catch (Exception ex) {
         Logger.getLogger(pruebasLienzo.class.getName()).log(Level.SEVERE, null, ex);
     }
     }
     
         
public void guardarComo() throws Exception{
  
//String nombre = "";
//JFileChooser Ventana=new JFileChooser(System.getProperty("user.dir"));
Ventana.showSaveDialog(this);
File GUARDAR =Ventana.getSelectedFile();
path = Ventana.getSelectedFile().getAbsolutePath(); //Obtengo path.
if(!GUARDAR.exists())
{
//nombre=Ventana.getSelectedFile().getName();
    
FileWriter GUARDADO=new FileWriter(GUARDAR+".lz");      
         
        JTextArea encontro=ObtenerAreaTexto();
        //jTabbedPane14.addTab(Jtreevar,new JScrollPane(textPa));
         GUARDADO.write(encontro.getText());
         GUARDADO.close();
                
                

}else
{
    int n=JOptionPane.showConfirmDialog(null,"El archivo ya existe desea reemplazarlo");
    if(n==JOptionPane.YES_OPTION){
          PrintWriter ouPt=new PrintWriter(new FileWriter(GUARDAR));
          edicion.getDocument().insertString(0, "", null);
                    ouPt.write(edicion.getText());
                    ouPt.close();
    }
}
} 

     public void compilar() throws Exception{
        tablaSimbolos.clear();
        hora();
               
         cantErrores=0;
         cantSimbolos=0;
          indiceDePestanha=jTabbedPane1.getSelectedIndex();
         JTextArea pru=ObtenerAreaTexto();
              
        
        String sentence = pru.getText();//txtEntrada.getText();
        
        Graphviz dibujo=new Graphviz();
        NodoArbol arbol;
        InputStream is = new ByteArrayInputStream(sentence.getBytes());
        if(calc == null) calc = new Analizador1.proyecto(is);
        else calc.ReInit(is);
        try
        {
            arbol=calc.Programa();
            dibujo.dibujarArbol(arbol);
            Acciones_Semanticas pasada1=new Acciones_Semanticas();
            // pasada1.dibujarArbol(declaracion);
            pasada1.evaluar_arbol(arbol,0);
            setTablaSimbolos(pasada1.getTablaSimbolos());
            
            
            Acciones_Semanticas2 pasada2=new Acciones_Semanticas2();
            pasada2.setTablaSimbolosTemporal(getTablaSimbolos());
            tablaSimbolos.clear();
            pasada2.evaluar_arbol(arbol,0);
            setTablaSimbolos(pasada2.getTablaSimbolos());
             LienzoDibujo ld = new LienzoDibujo(this, true, "C:\\Users\\Alberth\\Pictures");
            System.out.println("paso");
//        ld.dibujarOvalo(100, 100,50,100,"BA3519", 1);
//        ld.dibujarRectangulo(200, 200,50,100,"BA3519", 1);
//        ld.dibujarTexto("holita",100, 100,"BA3519");
//        ld.dibujarPunto(300, 300,"BA3519",50, 1);
           // ld.setVisible(true);
            Acciones_Semanticas3 pasada3=new Acciones_Semanticas3(ld);
            pasada3.setTablaSimbolos(getTablaSimbolos());
            tablaSimbolos.clear();
            pasada3.evaluar_arbol(arbol,0);
            setTablaSimbolos(pasada3.getTablaSimbolos());
            
        }
        catch (Exception e)
        {
            //txtAreaOut.setText("error in expression.\n"+ e.getMessage());
            System.out.println("Error en expresion.\n"+e.getMessage());
            imprimirConsola(0,0,"",e.getMessage());
        }
        catch (Error e)
        {
            //txtAreaOut.setText("error in expression.\n"+ e.getMessage());
            System.out.println("Error en expresion.\n"+e.getMessage());
            imprimirConsola(0,0,"",e.getMessage());
        }
        finally
        {}       

            }
     
      public static void  imprimirConsola(int linea,int columna,String tipoError,String descripcion) throws Exception{
    tablaErrores+="<tr><td>"+linea+"</td><td>"+columna+"</td><td>"+tipoError+"</td><td>"+descripcion+"</td></tr>";
    cantErrores+=1;
        }
      
      public void mostrarErrores(){
          // compilar();
        if(cantErrores==0){
            JOptionPane.showMessageDialog( rootPane, "No existen errores", "Sin errores", JOptionPane.WARNING_MESSAGE); //Mensaje por si se prduce un error
        }else{
            tablaErrores+="</table></body></html>";
            mostrarHtml html=new mostrarHtml();
            html.mostrar(tablaErrores,"ERRORES");
            html.setVisible(true);
        }
      }

   private String mes(int mes){
        String mesA="";
        switch(mes){
            case 1: mesA= "Enero"; break;
            case 2: mesA= "Febrero";break;
            case 3: mesA= "Marzo";break;
            case 4: mesA= "Abril";break;
            case 5: mesA= "Mayo";break;
            case 6: mesA= "Junio";break;
            case 7: mesA= "Julio";break;
            case 8: mesA= "Agosto";break;
            case 9: mesA= "Septiembre";break;
            case 10: mesA= "Octubre";break;
            case 11: mesA= "Noviembre";break;
            case 12: mesA= "Diciembre";break;
        }
        return mesA;
    }

   public void hora(){
       
       hora =calendario.get(Calendar.HOUR);
        minutos = calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND);
        dia=calendario.get( Calendar.DAY_OF_MONTH);
        mes=calendario.get(Calendar.MONTH);
        anho=calendario.get(Calendar.YEAR);
        int ampm=calendario.get(Calendar.AM_PM);
        diaL="Dia de ejecucion : "+dia +" de "+mes(mes+1)+" de "+anho+"\n";
        horaL="Hora de ejecucion : "+hora + ":" + minutos + ":" + segundos+" "+ampm(ampm)+"\n";
        tablaErrores="<html><head><title>ERRORES</title></head><body><h1>ERRORES</h1><h1>"+diaL+"</h1><h1>"+horaL+"</h1><center><table border=1><tr><th>Linea</th><th>Columna</th><th>Tipo Error</th><th>Descripcion</th></tr>";
        tablaSimbolosM="<html><head><title>TABLA DE SIMBOLOS</title></head><body><h1>TABLA DE SIMBOLOS</h1><h1>"+diaL+"</h1><h1>"+horaL+"</h1><center><table border=1><tr><th>No.</th><th>NOMBRE</th><th>VALOR</th><th>TIPO</th><th>ROL</th><th>AMBITO</th><th>UBICACION</th><th>PARAMETROS</th><th>POSICION</th><th>TAMANHO</th></tr>";
   }
   
   public void mostrarTablaSimbolos(){
          // compilar();
        if(cantSimbolos==0){
            JOptionPane.showMessageDialog( rootPane, "No existen simbolos", "TABLA DE SIMBOLOS", JOptionPane.WARNING_MESSAGE); //Mensaje por si se prduce un error
        }else{
            for(int c=0;c<tablaSimbolos.size();c++){
                tablaSimbolosM+="<tr><td>"+(c+1)+"</td><td>"+tablaSimbolos.get(c).nombre+"</td><td>"+tablaSimbolos.get(c).valor+"</td><td>"+tablaSimbolos.get(c).tDato+"</td><td>"+tablaSimbolos.get(c).tipo+"</td><td>"+tablaSimbolos.get(c).ambito+"</td><td>"+tablaSimbolos.get(c).ubicacion+"</td><td>"+tablaSimbolos.get(c).parametros+"</td><td>"+tablaSimbolos.get(c).posicion+"</td><td>"+tablaSimbolos.get(c).tamanho+"</td></tr>";
                //cantSimbolos+=1;
            }
            tablaSimbolosM+="</table></body></html>";
            mostrarHtml html=new mostrarHtml();
            html.mostrar(tablaSimbolosM,"TABLA DE SIMBOLOS");
            html.setVisible(true);
        }
      }
   
   
      private String ampm(int ampmD){
          String ampm="";
        switch(ampmD){
            case 1: ampm= "p.m."; break;
            case 0: ampm= "a.m.";break;
        }
        return ampm;
    }

       private void abrir(String archivo) {
  //ruta del archivo en el pc
  String file = new String("C:\\ManualesCompi2\\"+archivo+".pdf"); 
   
 try{ 
   //definiendo la ruta en la propiedad file
   Runtime.getRuntime().exec("cmd /c start "+file);
     
   }catch(IOException e){
      e.printStackTrace();
   } 
       }
              
}// no tocar
